"""Initial migration

Revision ID: 5361c93ce532
Revises: 
Create Date: 2023-10-13 18:41:30.154221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5361c93ce532'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('map',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('player_name', sa.String(length=15), nullable=False),
    sa.Column('player_champion_id', sa.String(length=12), nullable=False),
    sa.Column('opponent_name', sa.String(length=15), nullable=False),
    sa.Column('opponent_champion_id', sa.String(length=12), nullable=False),
    sa.Column('map_id', sa.String(length=10), nullable=False),
    sa.Column('recording_path', sa.String(), nullable=True),
    sa.Column('screenshot_path', sa.String(), nullable=True),
    sa.Column('discord_message_id', sa.Integer(), nullable=True),
    sa.Column('youtube_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['map.code'], ),
    sa.ForeignKeyConstraint(['opponent_champion_id'], ['champion.name'], ),
    sa.ForeignKeyConstraint(['player_champion_id'], ['champion.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    from quad.models import Champion, Map

    op.bulk_insert(
        Champion.__table__,
        [
            {"name": "Nyx"},
            {"name": "Anarki"},
            {"name": "Slash"},
            {"name": "Athena"},
            {"name": "Visor"},
            {"name": "Ranger"},
            {"name": "Doom"},
            {"name": "Strogg"},
            {"name": "Eisen"},
            {"name": "DK"},
            {"name": "Galena"},
            {"name": "BJ"},
            {"name": "Sorlag"},
            {"name": "Keel"},
            {"name": "Scalebearer"},
            {"name": "Clutch"},
        ]
    )

    op.bulk_insert(
        Map.__table__,
        [
            {"code": "awoken",   "name": "Awoken"},
            {"code": "bc",       "name": "Blood Covenant"},
            {"code": "ck",       "name": "Corrupted Keep"},
            {"code": "crucible", "name": "Crucible"},
            {"code": "deep",     "name": "Deep Embrace"},
            {"code": "insomnia", "name": "Insomnia"},
            {"code": "molten",   "name": "Molten Falls"},
            {"code": "ruins",    "name": "Ruins of Sarnath"},
            {"code": "vale",     "name": "Vale of Pnath"},
            {"code": "exile",    "name": "Exile"},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.drop_table('player')
    op.drop_table('map')
    op.drop_table('champion')
    # ### end Alembic commands ###
