"""empty message

Revision ID: cbd2831b73af
Revises: 5361c93ce532
Create Date: 2024-03-19 13:40:20.336710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd2831b73af'
down_revision = '5361c93ce532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_vocabulary',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('text_read', sa.VARCHAR(), nullable=False),
                    sa.Column('text', sa.VARCHAR(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_vocabulary')

    # ### end Alembic commands ###
