name: Test and Build
run-name: Testing and building Quad
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install project
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest coverage
          pytest
      - name: Build Wheel
        run: |
          pip install build
          LINE=`python -m build --wheel | grep "Successfully built"`
          BUILD_FILE=${LINE#"Successfully built "}
          deactivate
          source /srv/quad/.venv/bin/activate
          pip install dist/$BUILD_FILE
