name: Test and Build
run-name: Testing and building Quad
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.2' 
      - run: pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest coverage
          pytest
