name: Test and Build
run-name: Testing and building Quad
on: 
  push:
    branches:    
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install project
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pip install pytest coverage
          pytest
      - name: Build and Deploy
        run: |
          source .venv/bin/activate
          pip install build
          LINE=`python -m build --wheel | grep "Successfully built"`
          BUILD_FILE=${LINE#"Successfully built "}
          deactivate
          source /srv/quad/.venv/bin/activate
          systemctl stop quad.service || :
          pip freeze --exclude quad | xargs pip uninstall -y
          pip uninstall -y quad
          pip install --upgrade --force-reinstall dist/$BUILD_FILE
          mv dist/$BUILD_FILE /var/opt/quad/backups/wheels/
          systemctl start quad.service
