name: Test and Build
run-name: Testing and building Quad
on: 
  push:
    branches:    
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install project
        run: |
          apt -y install python3-pip python3-venv tesseract-ocr
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .
      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pip install pytest coverage
          pytest
      - name: Build and Deploy
        run: |
          mkdir -p /srv/quad
          source .venv/bin/activate
          pip install build
          LINE=`python -m build --wheel | grep "Successfully built"`
          BUILD_FILE=${LINE#"Successfully built "}
          deactivate
          cat /srv/quad/.venv/bin/activate > /dev/null || python3 -m venv /srv/quad/.venv && source /srv/quad/.venv/bin/activate
          systemctl stop quad.service || :
          pip freeze --exclude quad | xargs pip uninstall -y || :
          pip uninstall -y quad
          pip install --upgrade --force-reinstall dist/$BUILD_FILE
          ln -s /etc/systemd/system/quad.service /srv/quad/quad.service
          systemctl enable quad.service
          flask --app quad db upgrade
          mkdir -p /var/opt/quad/backups/wheels/
          mv dist/$BUILD_FILE /var/opt/quad/backups/wheels/
          systemctl start quad.service
